# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_creted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='creted',
        ),
    ]
